# https://taskfile.dev

version: "3"

tasks:
  test:
    cmds:
      - go test -count=1 -race -v

  update/minimp3:
    cmds:
      - curl -o minimp3.h https://raw.githubusercontent.com/lieff/minimp3/refs/heads/master/minimp3.h
      - curl -o minimp3_ex.h https://raw.githubusercontent.com/lieff/minimp3/refs/heads/master/minimp3_ex.h
    sources:
      - Taskfile.yml
    generates:
      - minimp3.h
      - minimp3_ex.h

  update/mp3:
    cmds:
      - curl -o testdata/piano.mp3 https://samples.ffmpeg.org/A-codecs/suite/MP3/piano.mp3
      - curl -o testdata/44khz128kbps.mp3 https://samples.ffmpeg.org/A-codecs/suite/MP3/44khz128kbps.mp3
    sources:
      - Taskfile.yml
    generates:
      - testdata/piano.mp3
      - testdata/44khz128kbps.mp3

  update/pcm:
    deps: [update/mp3]
    cmds:
      - go test -count=1 -race -v -write-golden=true
    sources:
      - testdata/piano.mp3
      - testdata/44khz128kbps.mp3
    generates:
      - testdata/piano_s16le_44.1khz_stereo.pcm
      - testdata/44khz128kbps_s16le_44.1khz_stereo.pcm

  play/pcm:
    cmds:
      - ffplay -autoexit -f s16le -ar 44.1k -ch_layout stereo testdata/piano_s16le_44.1khz_stereo.pcm
      - ffplay -autoexit -f s16le -ar 44.1k -ch_layout stereo testdata/44khz128kbps_s16le_44.1khz_stereo.pcm

  run/docker:
    cmds:
      - docker build -t {{.DOCKER_IMAGE}} .
      - "cat ./testdata/44khz128kbps.mp3 | docker run --rm -i {{.DOCKER_IMAGE}} | ffplay -autoexit -i pipe:"
    vars:
      DOCKER_IMAGE: cowork-ai/go-minimp3
